---
title: "Relationship Between Dominant Hand and Grip Strength in Young Adults"
author: "Julia Curry, "
date: "2023-12-12"
output: html_document
---

# Introduction 

STILL WORKING ON INTRO, FIRST SENTENCE I ADDED BECAUSE IT SHOWS PURPOSE. COPIED NICOLE'S INTRO FROM DOC, NO REFERENCES ADDED YET. 

The knowledge of how changes in body angle and dominant hand use affect the strength of the grip can be used to design environments and tools to maximize biomechanical abilities.

Grip strength is determined by the coordinated interaction of the brain, nerves, muscles, bones, and joints, enabling the exertion of maximum force through the hand's flexor muscles and finger joints under normal conditions. It is commonly assessed as a component of hand function and is an indicator of patients’ ability for daily activities that involve hand usage. Grip strength measurement gives insights into the overall strength and function of the forearm and hand muscles, which are crucial assessments for hand rehabilitation programs. In this paper, the researchers measured the correlation between carrying angle (the angle between the forearm and the upper arm) and grip strength among the 203 participants with a mean age of 22.95 ± 2.11. The results showed a weak negative correlation between carrying angle and grip strength on the left side, but no significant correlation on the right side. In our study, we aimed to assess the correlation between 8 carrying angles (180 – 22.5, with 12.5 increments) with the grip strength in dominant and nondominant hands of 5 college students. 

INSTRUCTIONS 

Frame the questions, indicating why they are important, what background work has been done in this realm, and how you will answer them. Please include at least one reference to support the summary of previous work. Note: this can be done easily by refiguring the introduction to this project report.

# Methods 

In order to assess the effect of dominant versus non-dominant hand grip strength we measured force data for 8 different angle positions and compared results for dominant hand and non-dominant hand. Our data consisted of 16 data points for 5 different individuals. In order to obtain data we designed and constructed a portable Arduino-based force-data acquisition system (DAQ).

1. DAQ Design components

100-kg S-type Load cell with HX711 amplifier 

Arduino Uno microcontroller 

2. Data Collection 

Constructed a ganiometer. Then, found the center of the elbow joint in lateral view and marked this position with a marker. From that point, we marked a line along the lateral margin of the radius. We then poked a hole through the center of the ganiometer to affix it to the upper arm so that the center aligns with the mark at the elbow and the 0-180angle axis aligns with the long axis of the humerus. 

3. Data Collection Isometric MVCs

Then, in order to use the ganiometer to collect data from 8 arm angles. We tested grip strength at the angles of 180, 157.5, 135, 117.5, 90, 67.5, 45, and 22.5. We moved through the 8 arm angles by rotating our bodies about the hips. 

4. WHAT WE DID IN CODE TO TEST 
 
# Results 

Include any appropriate figures or tables and a narrative of the main results that are important to answering the questions.

# Discussion 

Succinctly declare how the results relate to the question and how they compare to previous work devoted to the topic. In addition, be sure to comment on the importance of your findings to the broader topic at hand.

The Introduction and Discussion sections should include no fewer than three references to primary literature sources (i.e., scientific papers) between them. These references should be integrated using @ BibTex tags that automatically place the references in the document using the associated .bib file.

# Author Contributions 

Julia Curry: Helped set up Arduino unit, Created Skeleton of project report, Wrote Methods. 


# References 
