---
title: "TITLE"
author: "Julia Curry, "
date: "2023-12-12"
output: html_document
---

# Introduction 

Frame the questions, indicating why they are important, what background work has been done in this realm, and how you will answer them. Please include at least one reference to support the summary of previous work. Note: this can be done easily by refiguring the introduction to this project report.

# Methods 

Explicitly state how you answered the questions, including a narrative of all the analyses both qualitative and quantitative.
 
# Results 

Include any appropriate figures or tables and a narrative of the main results that are important to answering the questions.

# Discussion 

Succinctly declare how the results relate to the question and how they compare to previous work devoted to the topic. In addition, be sure to comment on the importance of your findings to the broader topic at hand.

The Introduction and Discussion sections should include no fewer than three references to primary literature sources (i.e., scientific papers) between them. These references should be integrated using @ BibTex tags that automatically place the references in the document using the associated .bib file.

# Author Contributions 

# References 